=== easyXpat/procedure-service/data/json/steps.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Step",
  "required" : [
    "id",
    "procedure_id",
    "name",
    "description",
    "rank"
  ],
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "description": "UUID to identify the step"
    },
    "procedure_id": {
      "type": "string",
      "description": "UUID to identify the procedure this step belongs to"
    },
    "name": {
      "type": "string",
      "description": "name of the step"
    },
    "rank": {
      "type": "integer",
      "description": "rank for the step"
    },
    "description": {
      "type": "string",
      "description": "description"
    },
    "created_at": {
      "type": "string",
      "description": "UTC datetime when record was created",
      "format": "date-time"
    },
    "updated_at": {
      "type": "string",
      "description": "UTC datetime when record was last updated",
      "format": "date-time"
    }
  }
}

=== easyXpat/procedure-service/data/json/steps.json
[
  {
    "id": "11d1de77-12d3-449b-801c-bb90889b7ed4",
    "procedure_id": "09e1ae77-52b1-449b-801c-bb90357b7ed4",
    "name": "Step 1",
    "rank": 1,
    "description": "My first step",
    "created_at": "2021-03-22T23:56:15.353842Z",
    "updated_at": "2021-03-23T00:27:51.82595Z"
  },
  {
    "id": "22d1de77-12d3-449b-801c-bb90889b7ed4",
    "procedure_id": "09e1ae77-52b1-449b-801c-bb90357b7ed4",
    "name": "Step 2",
    "rank": 2,
    "description": "My second step",
    "created_at": "2021-03-22T23:56:15.353842Z",
    "updated_at": "2021-03-23T00:27:51.82595Z"
  },
  {
    "id": "33d1de77-12d3-449b-801c-bb90889b7ed4",
    "procedure_id": "09e1ae77-52b1-449b-801c-bb90357b7ed4",
    "name": "Step 3",
    "rank": 3,
    "description": "My third step",
    "created_at": "2021-03-22T23:56:15.353842Z",
    "updated_at": "2021-03-23T00:27:51.82595Z"
  }
]
